"use client";

import { useState, useEffect } from "react";
import { useQuery, useMutation, useAction } from "convex/react";
import { api } from "@/convex/_generated/api";
import { PageHeader } from "@/components/layout/PageHeader";
import { Building2, FileText, Upload, RefreshCw, AlertTriangle, CheckCircle, Loader2, Printer } from "lucide-react";
import { Id } from "@/convex/_generated/dataModel";
import AnalysisReport from "@/components/planning/AnalysisReport";
import { useParams } from "next/navigation";

export default function ProjectDashboard() {
    const params = useParams();
    const projectId = params.id as Id<"civic_projects">;
    const project = useQuery(api.civic.getProject, { id: projectId });
    const addComments = useMutation(api.civic.addComments);
    const analyzeProject = useAction(api.ai.analyzeProject);

    const [newComments, setNewComments] = useState("");
    const [isAnalyzing, setIsAnalyzing] = useState(false);

    const handleAddComments = async () => {
        if (!newComments.trim()) return;
        await addComments({ projectId, newText: newComments });
        setNewComments("");
    };

    const handleAnalyze = async () => {
        setIsAnalyzing(true);
        try {
            await analyzeProject({ projectId });
        } catch (e) {
            console.error(e);
        } finally {
            setIsAnalyzing(false);
        }
    };

    const handlePrint = () => {
        window.print();
    };

    if (project === undefined) return <div className="p-8"><Loader2 className="animate-spin" /></div>;
    if (project === null) return <div className="p-8">Project not found</div>;

    return (
        <div className="min-h-screen bg-slate-50 text-slate-900 font-sans p-8 print:bg-white print:p-0">
            <style jsx global>{`
                @media print {
                    @page {
                        margin-bottom: 0;
                    }
                    body {
                        -webkit-print-color-adjust: exact;
                    }
                }
            `}</style>
            <div className="print:hidden">
                <PageHeader
                    title={project.title}
                    description={`Reference: ${project.planningRef}`}
                    icon={<Building2 size={24} />}
                    themeColor="teal"
                    action={
                        <div className="flex items-center gap-3">
                            <button
                                onClick={handlePrint}
                                className="p-3 bg-white border border-slate-200 text-slate-600 rounded-lg hover:bg-slate-50 hover:text-slate-900 transition-colors"
                                title="Print Executive Brief"
                            >
                                <Printer size={20} />
                            </button>
                            {project.status === "outdated" ? (
                                <button
                                    onClick={handleAnalyze}
                                    disabled={isAnalyzing}
                                    className="flex items-center gap-2 px-6 py-3 bg-amber-500 hover:bg-amber-600 text-white font-bold rounded-lg shadow-lg shadow-amber-500/25 animate-pulse"
                                >
                                    {isAnalyzing ? <Loader2 className="animate-spin" /> : <RefreshCw size={20} />}
                                    Update Analysis
                                </button>
                            ) : (
                                <div className="flex items-center gap-2 text-teal-600 font-medium bg-teal-50 px-4 py-2 rounded-lg border border-teal-200">
                                    <CheckCircle size={20} />
                                    Analysis Up to Date
                                </div>
                            )}
                        </div>
                    }
                />
            </div>

            {/* Print Header */}
            <div className="hidden print:block mb-8 border-b-2 border-slate-900 pb-4">
                <div className="flex justify-between items-end">
                    <div>
                        <h1 className="text-3xl font-bold text-slate-900 mb-2">{project.title}</h1>
                        <p className="text-lg text-slate-600 font-mono">Ref: {project.planningRef}</p>
                    </div>
                    <div className="text-right">
                        <div className="text-sm text-slate-500">Generated by</div>
                        <div className="text-xl font-bold text-teal-700">Vectis One CivicOS</div>
                    </div>
                </div>
            </div>

            <div className="grid grid-cols-1 lg:grid-cols-3 gap-8 print:block">
                {/* Left Column: Evidence Locker (Hidden on Print) */}
                <div className="lg:col-span-1 space-y-6 print:hidden">
                    <div className="bg-white p-6 rounded-xl border border-slate-200 shadow-sm">
                        <h3 className="text-lg font-bold mb-4 flex items-center gap-2">
                            <Upload size={20} className="text-teal-600" />
                            Add Representation
                        </h3>
                        <textarea
                            className="w-full h-48 p-3 border border-slate-200 rounded-lg focus:ring-2 focus:ring-teal-500 outline-none text-sm font-mono mb-4 resize-none"
                            placeholder="Paste new emails or comments here..."
                            value={newComments}
                            onChange={e => setNewComments(e.target.value)}
                        />
                        <button
                            onClick={handleAddComments}
                            disabled={!newComments.trim()}
                            className="w-full py-2 bg-slate-900 text-white rounded-lg font-medium hover:bg-slate-800 disabled:opacity-50"
                        >
                            Add to Case File
                        </button>
                    </div>

                    <div className="bg-white p-6 rounded-xl border border-slate-200 shadow-sm">
                        <h3 className="text-lg font-bold mb-4 flex items-center gap-2">
                            <FileText size={20} className="text-slate-400" />
                            Case History
                        </h3>
                        <div className="space-y-3">
                            {project.rawComments.map((_, idx) => (
                                <div key={idx} className="flex items-center justify-between p-3 bg-slate-50 rounded-lg border border-slate-100">
                                    <span className="text-sm font-medium text-slate-700">Batch #{idx + 1}</span>
                                    <span className="text-xs text-slate-400">Uploaded</span>
                                </div>
                            ))}
                            {project.rawComments.length === 0 && (
                                <p className="text-sm text-slate-400 italic">No documents uploaded yet.</p>
                            )}
                        </div>
                    </div>
                </div>

                {/* Right Column: Intelligence (Full Width on Print) */}
                <div className="lg:col-span-2 print:w-full">
                    {project.lastAnalysis ? (
                        <AnalysisReport
                            data={project.lastAnalysis}
                            rawComments={project.rawComments}
                        />
                    ) : (
                        <div className="bg-white p-12 rounded-xl border border-slate-200 border-dashed text-center print:hidden">
                            <div className="w-16 h-16 bg-slate-50 rounded-full flex items-center justify-center mx-auto mb-4 text-slate-400">
                                <Building2 size={32} />
                            </div>
                            <h3 className="text-lg font-bold text-slate-900 mb-2">Awaiting Analysis</h3>
                            <p className="text-slate-500 mb-6">
                                Upload comments and run the analysis to generate insights.
                            </p>
                        </div>
                    )}
                </div>
            </div>

            {/* Signature Block (Print Only) */}
            <div className="hidden print:block mt-12 pt-4 border-t border-slate-200 break-inside-avoid">
                <div className="flex justify-between items-end">
                    <div className="w-64">
                        <div className="border-b border-slate-400 h-8 mb-2"></div>
                        <p className="text-xs text-slate-500 uppercase tracking-wider">Planning Officer Signature</p>
                    </div>
                    <div className="text-xs text-slate-400">
                        Generated on {new Date().toLocaleDateString()} at {new Date().toLocaleTimeString()}
                    </div>
                </div>
            </div>
        </div>
    );
}